# Generated by Django 4.2.1 on 2023-06-04 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('business', 'Business'), ('web development', 'Web Development'), ('mobile development', 'Mobile Development'), ('machine learning', 'Machine Learning')], default='machine learning', max_length=100)),
                ('summary', models.CharField(max_length=250)),
                ('cover', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 6, 4, 11, 9, 0, 974187))),
                ('content', models.TextField()),
                ('trendy', models.BooleanField(default=False)),
            ],
        ),
    ]
